# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        swift: [ "5.8", "5.9" ]
        destination: [platform=iOS Simulator,OS=14.5,name=iPhone 12,platform=tvOS Simulator,OS=14.5,name=Apple TV,platform=watchOS Simulator,OS=7.4,name=Apple Watch Series 6 - 44mm]
        
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test -destination "$destination"

  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Swift
      uses: actions/setup-swift@v2
      with:
        swift-version: '5.5'

    - name: Build and Run Ubuntu Tests
      run: swift test
